.PHONY: clean All

All:
	@echo "----------Building project:[ Nul-Versie - Debug ]----------"
	@cd "Nul-Versie" && "$(MAKE)" -f  "Nul-Versie.mk"
clean:
	@echo "----------Cleaning project:[ Nul-Versie - Debug ]----------"
	@cd "Nul-Versie" && "$(MAKE)" -f  "Nul-Versie.mk" clean
