#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := IRSensorController.cpp IRSensor.cpp IRLed.cpp IRLedController.cpp GameTimeControl.cpp OLEDControl.cpp GameData.cpp GameControl.cpp DebugState.cpp KeypadControl.cpp


# header files in this project
HEADERS := IRSensorController.hpp IRSensor.hpp COMMANDS.hpp IRLed.hpp IRLedController.hpp GameTimeControl.hpp OLEDControl.hpp GameData.hpp GameControl.hpp DebugState.hpp GameStateInterface.hpp StateCollection.hpp KeypadControl.hpp GameControlInterface.hpp

# other places to look for files for this project
SEARCH  := C:\Users\marte\OneDrive\Documenten\Studie\HU\Thema opdracht devices\TekTeamOne\Software\FinalVersion\Lasertag

# set BMPTK to the next higher directory and defer to the Makefile.due
BMPTK := $(BMPTK)../
include $(BMPTK)Makefile.due
